name: daily EA_WAK update

on:
  push:
    branches:
      - master
  schedule:
    - cron: "30 18 * * *"

jobs:
  update_page:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: download EA_WAK data
        run: cd .github/workflows/ && env python3 ./download_EA_WAK.py && cd ../../
      - name: Commit files
        run: |
          git config --local user.name  ${{ github.actor }}
          git add ./data_EA_WAK/*.html
          git commit -m "daily EA_WAK update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true 
